version: "3"
services:
    mysql:
        image: mysql:8.0
        command:
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        volumes:
          - ./data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          
